######
# should succeed and return a configuration object
GET https://configuration-service.examples.oleksiipopov.com/edge
origin: https://prod.config-demo.examples.oleksiipopov.com

######
# should fail with 4xx
GET https://configuration-service.examples.oleksiipopov.com/edge
origin: https://google.com

######
# should succeed d return a configuration object
GET https://configuration-service.examples.oleksiipopov.com/by-key?environment=base

######
# should succeed d return a configuration object
GET https://configuration-service.examples.oleksiipopov.com/by-key?environment=production

######
# should succeed, but return the fallback allowed origin header, so the client fails with CORS error
OPTIONS https://configuration-service.examples.oleksiipopov.com/edge
origin: https://google.com

######
# should succeed and return current origin header as an allowed one
OPTIONS https://configuration-service.examples.oleksiipopov.com/by-key?environment=base
origin: http://localhost:9000

######
# should succeed, but return the fallback allowed origin header, so the client fails with CORS error
OPTIONS https://configuration-service.examples.oleksiipopov.com/by-key?environment=base
origin: http://localhost:12345

######
