GET https://configuration-service.examples.oleksiipopov.com/edge
origin: https://prod.config-demo.examples.oleksiipopov.com

######

GET https://configuration-service.examples.oleksiipopov.com/edge
origin: https://google.com

######

OPTIONS https://configuration-service.examples.oleksiipopov.com/edge
origin: https://google.com

######

GET https://configuration-service.examples.oleksiipopov.com/by-key?environment=base

######

GET https://configuration-service.examples.oleksiipopov.com/by-key?environment=production

######

OPTIONS https://configuration-service.examples.oleksiipopov.com/by-key?environment=base
origin: http://localhost:9000

######

OPTIONS https://configuration-service.examples.oleksiipopov.com/by-key?environment=base
origin: http://localhost:12345

######
